"""Tests for reading a yarn.lock.

Yarn is the easier of the two lock formats. It is flat, and every entry is
keyed by the requirement that produced it - `express@4.17.1` - so resolving an
edge is a dictionary lookup rather than a walk up a directory tree. What it
does need is two readers, because yarn 1 and berry write different files.

Both are exercised against locks yarn itself generated, under
tests/fixtures/npm/yarn-v1 and yarn-berry.
"""

import json
from pathlib import Path

import pytest

from scanner.manifests import ManifestError, yarn_lock

FIXTURES = Path(__file__).parent.parent / "fixtures" / "npm"


def project(directory: Path, dependencies: dict, lock: str) -> Path:
    (directory / "package.json").write_text(
        json.dumps({"name": "x", "version": "1.0.0", "dependencies": dependencies})
    )
    (directory / "yarn.lock").write_text(lock)
    return directory / "package.json"


def names_in(graph) -> set[str]:
    return {f"{node.key.name}@{node.key.version}" for node in graph.nodes.values()}


V1 = """\
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


express@4.17.1:
  version "4.17.1"
  resolved "https://registry.yarnpkg.com/express/-/express-4.17.1.tgz#4491fc"
  dependencies:
    debug "2.6.9"

debug@2.6.9:
  version "2.6.9"
  dependencies:
    ms "2.0.0"

ms@2.0.0:
  version "2.0.0"
"""

BERRY = """\
# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 10
  cacheKey: 10c0

"express@npm:4.17.1":
  version: 4.17.1
  resolution: "express@npm:4.17.1"
  dependencies:
    debug: "npm:2.6.9"
  languageName: node
  linkType: hard

"debug@npm:2.6.9":
  version: 2.6.9
  resolution: "debug@npm:2.6.9"
  languageName: node
  linkType: hard
"""


# --- yarn 1 ----------------------------------------------------------------


def test_a_v1_lock_is_read(tmp_path: Path) -> None:
    _, graph = yarn_lock.parse(project(tmp_path, {"express": "4.17.1"}, V1))

    assert names_in(graph) == {"express@4.17.1", "debug@2.6.9", "ms@2.0.0"}


def test_a_v1_edge_resolves_by_name_and_range(tmp_path: Path) -> None:
    """`express` requires `debug "2.6.9"`, so the entry to find is the one keyed
    `debug@2.6.9`. No version comparison happens anywhere."""
    _, graph = yarn_lock.parse(project(tmp_path, {"express": "4.17.1"}, V1))
    express = next(k for k in graph.nodes if k.name == "express")

    assert [k.name for k in graph.nodes[express].children] == ["debug"]


def test_v1_depth_is_the_shortest_path(tmp_path: Path) -> None:
    _, graph = yarn_lock.parse(project(tmp_path, {"express": "4.17.1"}, V1))

    assert {n.key.name: n.depth for n in graph.nodes.values()} == {
        "express": 0,
        "debug": 1,
        "ms": 2,
    }


def test_one_v1_entry_can_answer_for_several_ranges(tmp_path: Path) -> None:
    """A single resolution often satisfies more than one requirement, and yarn
    writes them as one comma separated key. Both PyPI yarn.lock libraries leave
    that key joined, so a lookup for either range finds nothing - which is why
    this is read here rather than imported.
    """
    lock = """\
"@babel/generator@^7.29.7", "@babel/generator@^7.29.8":
  version "7.29.8"
"""
    _, graph = yarn_lock.parse(project(tmp_path, {"@babel/generator": "^7.29.7"}, lock))

    assert names_in(graph) == {"@babel/generator@7.29.8"}


def test_the_other_range_of_a_shared_entry_also_resolves(tmp_path: Path) -> None:
    lock = """\
"@babel/generator@^7.29.7", "@babel/generator@^7.29.8":
  version "7.29.8"
"""
    _, graph = yarn_lock.parse(project(tmp_path, {"@babel/generator": "^7.29.8"}, lock))

    assert names_in(graph) == {"@babel/generator@7.29.8"}


def test_an_unquoted_v1_key_is_read(tmp_path: Path) -> None:
    """yarn quotes a key only when it has to, so both forms appear in one file."""
    _, graph = yarn_lock.parse(project(tmp_path, {"express": "4.17.1"}, V1))

    assert "express@4.17.1" in names_in(graph)


def test_a_scoped_v1_package_keeps_its_scope(tmp_path: Path) -> None:
    lock = '"@babel/core@^7.0.0":\n  version "7.29.7"\n'
    _, graph = yarn_lock.parse(project(tmp_path, {"@babel/core": "^7.0.0"}, lock))

    assert names_in(graph) == {"@babel/core@7.29.7"}


# --- berry -----------------------------------------------------------------


def test_a_berry_lock_is_read(tmp_path: Path) -> None:
    _, graph = yarn_lock.parse(project(tmp_path, {"express": "4.17.1"}, BERRY))

    assert names_in(graph) == {"express@4.17.1", "debug@2.6.9"}


def test_a_berry_range_drops_the_npm_protocol(tmp_path: Path) -> None:
    """Berry writes `npm:^1.0.0` where yarn 1 writes `^1.0.0`. Stripping the
    protocol is what lets one lookup serve both formats and package.json."""
    _, graph = yarn_lock.parse(project(tmp_path, {"express": "4.17.1"}, BERRY))
    express = next(k for k in graph.nodes if k.name == "express")

    assert [k.name for k in graph.nodes[express].children] == ["debug"]


def test_the_metadata_block_is_not_a_package(tmp_path: Path) -> None:
    """`__metadata` is a berry header, not something to scan."""
    _, graph = yarn_lock.parse(project(tmp_path, {"express": "4.17.1"}, BERRY))

    assert not any("metadata" in k.name for k in graph.nodes)


# --- aliases, in both formats ----------------------------------------------


def test_an_aliased_package_is_named_by_the_registry(tmp_path: Path) -> None:
    """`"utils": "npm:lodash@4.17.15"` is lodash. Yarn has no `name` field the
    way npm does - the real name is inside the range itself."""
    lock = '"utils@npm:lodash@4.17.15":\n  version "4.17.15"\n'
    _, graph = yarn_lock.parse(project(tmp_path, {"utils": "npm:lodash@4.17.15"}, lock))

    assert names_in(graph) == {"lodash@4.17.15"}


def test_a_scoped_alias_keeps_its_scope(tmp_path: Path) -> None:
    lock = '"shim@npm:@babel/core@7.29.7":\n  version "7.29.7"\n'
    _, graph = yarn_lock.parse(project(tmp_path, {"shim": "npm:@babel/core@7.29.7"}, lock))

    assert names_in(graph) == {"@babel/core@7.29.7"}


# --- what the manifest asked for -------------------------------------------


def test_dev_dependencies_are_direct(tmp_path: Path) -> None:
    (tmp_path / "package.json").write_text(
        json.dumps({"name": "x", "dependencies": {}, "devDependencies": {"ms": "2.0.0"}})
    )
    (tmp_path / "yarn.lock").write_text('ms@2.0.0:\n  version "2.0.0"\n')

    parsed, graph = yarn_lock.parse(tmp_path / "package.json")

    assert [k.name for k in graph.roots] == ["ms"]
    assert len(parsed.dependencies) == 1


def test_a_local_path_dependency_is_skipped(tmp_path: Path) -> None:
    manifest = project(
        tmp_path, {"mine": "file:../mine", "ms": "2.0.0"}, 'ms@2.0.0:\n  version "2.0.0"\n'
    )

    parsed, graph = yarn_lock.parse(manifest)

    assert [s.content for s in parsed.skipped] == ["mine@file:../mine"]
    assert names_in(graph) == {"ms@2.0.0"}


# --- failure modes ---------------------------------------------------------


def test_a_missing_lock_names_the_command_that_makes_one(tmp_path: Path) -> None:
    (tmp_path / "package.json").write_text('{"name": "x"}')

    with pytest.raises(ManifestError) as raised:
        yarn_lock.parse(tmp_path / "package.json")

    assert "yarn install" in str(raised.value)


def test_a_requirement_with_no_entry_is_skipped(tmp_path: Path) -> None:
    manifest = project(tmp_path, {"ghost": "^1.0.0"}, 'ms@2.0.0:\n  version "2.0.0"\n')

    _, graph = yarn_lock.parse(manifest)

    assert graph.nodes == {}


def test_a_cycle_terminates(tmp_path: Path) -> None:
    lock = (
        'a@1.0.0:\n  version "1.0.0"\n  dependencies:\n    b "1.0.0"\n\n'
        'b@1.0.0:\n  version "1.0.0"\n  dependencies:\n    a "1.0.0"\n'
    )
    _, graph = yarn_lock.parse(project(tmp_path, {"a": "1.0.0"}, lock))

    assert names_in(graph) == {"a@1.0.0", "b@1.0.0"}


# --- against locks yarn actually wrote -------------------------------------


@pytest.mark.parametrize("fixture", ["yarn-v1", "yarn-berry"])
def test_a_real_lock_reads_the_same_packages_in_both_formats(fixture: str) -> None:
    """The same package.json, locked by yarn 1 and by berry. The two files look
    nothing alike and have to produce the same answer."""
    _, graph = yarn_lock.parse(FIXTURES / fixture / "package.json")

    assert "express@4.17.1" in names_in(graph)
    assert "lodash.merge@4.6.2" in names_in(graph)
    assert "@babel/core@7.29.7" in names_in(graph)


@pytest.mark.parametrize("fixture", ["yarn-v1", "yarn-berry"])
def test_a_real_alias_resolves_in_both_formats(fixture: str) -> None:
    _, graph = yarn_lock.parse(FIXTURES / fixture / "package.json")

    assert "lodash@4.17.15" in names_in(graph)
    assert not any(k.name == "utils" for k in graph.nodes)


@pytest.mark.parametrize("fixture", ["yarn-v1", "yarn-berry"])
def test_a_real_lock_has_no_dangling_edges(fixture: str) -> None:
    _, graph = yarn_lock.parse(FIXTURES / fixture / "package.json")

    dangling = [
        (node.key.name, child.name)
        for node in graph.nodes.values()
        for child in node.children
        if child not in graph.nodes
    ]

    assert dangling == []


def test_a_direct_package_reached_again_deeper_stays_direct(tmp_path: Path) -> None:
    """One yarn entry can answer several ranges, so two lookups reach one
    package. The shorter route is the one whose depth should survive."""
    lock = (
        '"async@^2.6.4", "async@2.6.4":\n  version "2.6.4"\n\n'
        'grunt@^1:\n  version "1.0.0"\n  dependencies:\n    async "2.6.4"\n'
    )
    manifest = project(tmp_path, {"async": "^2.6.4", "grunt": "^1"}, lock)

    _, graph = yarn_lock.parse(manifest)
    async_key = next(k for k in graph.nodes if k.name == "async")

    assert graph.nodes[async_key].depth == 0
    assert len([n for n in graph.nodes.values() if n.depth == 0]) == len(graph.roots)
