"""Tests for reading a package.json and its lock file.

There is no resolution step here: npm already decided every version and wrote
it down, so these check that we read the answer it recorded rather than work
one out. Most use a lock written inline, because the behaviour being pinned is
usually one nesting arrangement; the two under tests/fixtures/npm were
generated by npm itself.
"""

import json
from pathlib import Path

import pytest

from scanner.enums import EcoSystem, SkipReason
from scanner.manifests import package_lock

FIXTURES = Path(__file__).parent.parent / "fixtures" / "npm"


def write(directory: Path, manifest: dict, lock_packages: dict) -> Path:
    """Write a package.json and package-lock.json, and return the manifest."""
    root = {
        "dependencies": manifest.get("dependencies", {}),
        "devDependencies": manifest.get("devDependencies", {}),
        "optionalDependencies": manifest.get("optionalDependencies", {}),
    }
    (directory / "package.json").write_text(
        json.dumps({"name": "t", "version": "1.0.0", **manifest})
    )
    (directory / "package-lock.json").write_text(
        json.dumps({"lockfileVersion": 3, "packages": {"": root, **lock_packages}})
    )
    return directory / "package.json"


def names_in(graph) -> set[str]:
    return {f"{node.key.name}@{node.key.version}" for node in graph.nodes.values()}


# --- the packages a lock installs -----------------------------------------


def test_every_locked_package_becomes_a_node(tmp_path: Path) -> None:
    manifest = write(
        tmp_path,
        {"dependencies": {"a": "^1.0.0"}},
        {
            "node_modules/a": {"version": "1.2.3", "dependencies": {"b": "^2.0.0"}},
            "node_modules/b": {"version": "2.0.1"},
        },
    )

    _, graph = package_lock.parse(manifest)

    assert names_in(graph) == {"a@1.2.3", "b@2.0.1"}


def test_the_version_comes_from_the_lock_not_the_manifest(tmp_path: Path) -> None:
    """`^1.0.0` is a range; the lock says which release satisfied it."""
    manifest = write(
        tmp_path, {"dependencies": {"a": "^1.0.0"}}, {"node_modules/a": {"version": "1.9.4"}}
    )

    _, graph = package_lock.parse(manifest)

    assert names_in(graph) == {"a@1.9.4"}


def test_packages_are_npm_packages(tmp_path: Path) -> None:
    """The ecosystem is what OSV is asked about, so it has to be right."""
    manifest = write(
        tmp_path, {"dependencies": {"a": "1"}}, {"node_modules/a": {"version": "1.0.0"}}
    )

    _, graph = package_lock.parse(manifest)

    (node,) = graph.nodes.values()
    assert node.key.eco_system is EcoSystem.NPM


def test_a_scoped_package_keeps_its_scope(tmp_path: Path) -> None:
    manifest = write(
        tmp_path,
        {"dependencies": {"@babel/core": "^7.0.0"}},
        {"node_modules/@babel/core": {"version": "7.29.7"}},
    )

    _, graph = package_lock.parse(manifest)

    assert names_in(graph) == {"@babel/core@7.29.7"}


def test_an_entry_with_no_version_is_not_a_package(tmp_path: Path) -> None:
    """A `file:` or link entry names a location, not a release."""
    manifest = write(
        tmp_path,
        {"dependencies": {"a": "1", "local": "file:./local"}},
        {"node_modules/a": {"version": "1.0.0"}, "node_modules/local": {"resolved": "local"}},
    )

    _, graph = package_lock.parse(manifest)

    assert names_in(graph) == {"a@1.0.0"}


# --- nesting: the reason a lock path is not a package name ------------------


NESTED = {
    "node_modules/debug": {"version": "4.4.3", "dependencies": {"ms": "^2.1.3"}},
    "node_modules/ms": {"version": "2.1.3"},
    "node_modules/send": {"version": "0.17.1", "dependencies": {"debug": "2.6.9"}},
    "node_modules/send/node_modules/debug": {"version": "2.6.9", "dependencies": {"ms": "2.0.0"}},
    "node_modules/send/node_modules/ms": {"version": "2.0.0"},
}


def test_a_nested_copy_shadows_the_one_above_it(tmp_path: Path) -> None:
    """`send` requires debug 2.6.9 while the project has 4.4.3 at the top. Node
    looks in the requirer's own node_modules first, so `send` sees the nested
    one - which is why a lock path identifies a package here and a name cannot."""
    manifest = write(tmp_path, {"dependencies": {"debug": "^4", "send": "^0.17"}}, NESTED)

    _, graph = package_lock.parse(manifest)
    send = next(k for k in graph.nodes if k.name == "send")

    assert {k.version for k in graph.nodes[send].children if k.name == "debug"} == {"2.6.9"}


def test_the_same_package_can_be_installed_at_two_versions(tmp_path: Path) -> None:
    """Normal npm, and the reason this never goes through the resolver: that
    exists to collapse a name to one version."""
    manifest = write(tmp_path, {"dependencies": {"debug": "^4", "send": "^0.17"}}, NESTED)

    _, graph = package_lock.parse(manifest)

    assert {k.version for k in graph.nodes if k.name == "ms"} == {"2.0.0", "2.1.3"}


def test_a_requirement_falls_back_to_the_copy_above(tmp_path: Path) -> None:
    """Top level `debug` has no nested `ms`, so it uses the project's."""
    manifest = write(tmp_path, {"dependencies": {"debug": "^4", "send": "^0.17"}}, NESTED)

    _, graph = package_lock.parse(manifest)
    debug = next(k for k in graph.nodes if k.name == "debug" and k.version == "4.4.3")

    assert [k.version for k in graph.nodes[debug].children] == ["2.1.3"]


# --- what the manifest asked for -------------------------------------------


def test_direct_dependencies_come_from_the_manifest(tmp_path: Path) -> None:
    manifest = write(
        tmp_path,
        {"dependencies": {"a": "1"}},
        {
            "node_modules/a": {"version": "1.0.0", "dependencies": {"b": "1"}},
            "node_modules/b": {"version": "1.0.0"},
        },
    )

    _, graph = package_lock.parse(manifest)

    assert [k.name for k in graph.roots] == ["a"]


def test_depth_is_the_shortest_path_from_a_direct_dependency(tmp_path: Path) -> None:
    manifest = write(
        tmp_path,
        {"dependencies": {"a": "1"}},
        {
            "node_modules/a": {"version": "1.0.0", "dependencies": {"b": "1"}},
            "node_modules/b": {"version": "1.0.0", "dependencies": {"c": "1"}},
            "node_modules/c": {"version": "1.0.0"},
        },
    )

    _, graph = package_lock.parse(manifest)

    assert {n.key.name: n.depth for n in graph.nodes.values()} == {"a": 0, "b": 1, "c": 2}


def test_dev_dependencies_are_direct_too(tmp_path: Path) -> None:
    """A project installs its own devDependencies, so they are things it asked
    for. Leaving them out of the roots strands the whole dev subtree at no
    depth - which reads as `0 packages` rather than as a bug."""
    manifest = write(
        tmp_path,
        {"dependencies": {"a": "1"}, "devDependencies": {"d": "1"}},
        {"node_modules/a": {"version": "1.0.0"}, "node_modules/d": {"version": "9.0.0"}},
    )

    _, graph = package_lock.parse(manifest)

    assert sorted(k.name for k in graph.roots) == ["a", "d"]


def test_a_dependencys_dev_dependencies_are_not_installed(tmp_path: Path) -> None:
    """The asymmetry: your dev dependencies ship to your machine, a library's
    do not ship to anyone."""
    manifest = write(
        tmp_path,
        {"dependencies": {"a": "1"}},
        {
            "node_modules/a": {"version": "1.0.0", "devDependencies": {"jest": "1"}},
            "node_modules/jest": {"version": "1.0.0"},
        },
    )

    _, graph = package_lock.parse(manifest)
    a = next(k for k in graph.nodes if k.name == "a")

    assert graph.nodes[a].children == []


def test_optional_dependencies_are_included(tmp_path: Path) -> None:
    """fsevents is macOS only. A manifest scanned on Linux may be installed on
    a Mac, so this keeps them for the same reason the Python side keeps
    platform markers."""
    manifest = write(
        tmp_path,
        {"dependencies": {"a": "1"}, "optionalDependencies": {"fsevents": "^2"}},
        {"node_modules/a": {"version": "1.0.0"}, "node_modules/fsevents": {"version": "2.3.3"}},
    )

    _, graph = package_lock.parse(manifest)

    assert "fsevents@2.3.3" in names_in(graph)


def test_peer_dependencies_are_included(tmp_path: Path) -> None:
    """npm 7 and later install them."""
    manifest = write(
        tmp_path,
        {"dependencies": {"a": "1"}},
        {
            "node_modules/a": {"version": "1.0.0", "peerDependencies": {"react": "^18"}},
            "node_modules/react": {"version": "18.3.1"},
        },
    )

    _, graph = package_lock.parse(manifest)

    assert "react@18.3.1" in names_in(graph)


# --- aliases ---------------------------------------------------------------


def test_an_aliased_package_is_named_by_the_registry_not_the_folder(tmp_path: Path) -> None:
    """`"utils": "npm:lodash@4.17.15"` installs lodash into node_modules/utils.
    Reading the name off the path asks OSV about `utils`, which has nothing to
    report, and a package with six advisories comes back clean."""
    manifest = write(
        tmp_path,
        {"dependencies": {"utils": "npm:lodash@4.17.15"}},
        {"node_modules/utils": {"name": "lodash", "version": "4.17.15"}},
    )

    _, graph = package_lock.parse(manifest)

    assert names_in(graph) == {"lodash@4.17.15"}


def test_an_alias_is_still_a_direct_dependency(tmp_path: Path) -> None:
    manifest = write(
        tmp_path,
        {"dependencies": {"utils": "npm:lodash@4.17.15"}},
        {"node_modules/utils": {"name": "lodash", "version": "4.17.15"}},
    )

    _, graph = package_lock.parse(manifest)

    assert [k.name for k in graph.roots] == ["lodash"]


def test_an_edge_to_an_alias_names_the_real_package(tmp_path: Path) -> None:
    manifest = write(
        tmp_path,
        {"dependencies": {"a": "1"}},
        {
            "node_modules/a": {"version": "1.0.0", "dependencies": {"utils": "npm:lodash@4.17.15"}},
            "node_modules/utils": {"name": "lodash", "version": "4.17.15"},
        },
    )

    _, graph = package_lock.parse(manifest)
    a = next(k for k in graph.nodes if k.name == "a")

    assert [k.name for k in graph.nodes[a].children] == ["lodash"]


# --- what was not read -----------------------------------------------------


def test_a_local_path_dependency_is_recorded_as_skipped(tmp_path: Path) -> None:
    """Same treatment as `-e .` on the Python side: say what was not read
    rather than drop it silently."""
    manifest = write(
        tmp_path,
        {"dependencies": {"a": "1", "mine": "file:../mine"}},
        {"node_modules/a": {"version": "1.0.0"}},
    )

    parsed, _ = package_lock.parse(manifest)

    assert [(s.content, s.reason) for s in parsed.skipped] == [
        ("mine@file:../mine", SkipReason.LOCAL_PATH)
    ]


@pytest.mark.parametrize("spec", ["file:../mine", "link:../mine", "workspace:*"])
def test_every_local_reference_form_is_skipped(tmp_path: Path, spec: str) -> None:
    manifest = write(tmp_path, {"dependencies": {"mine": spec}}, {})

    parsed, _ = package_lock.parse(manifest)

    assert [s.reason for s in parsed.skipped] == [SkipReason.LOCAL_PATH]


def test_the_requirements_are_what_the_manifest_named(tmp_path: Path) -> None:
    """`requirements` is the count the report prints, so it counts what the
    file asked for, not what that turned out to install."""
    manifest = write(
        tmp_path,
        {"dependencies": {"a": "1"}, "devDependencies": {"d": "1"}},
        {
            "node_modules/a": {"version": "1.0.0", "dependencies": {"b": "1"}},
            "node_modules/b": {"version": "1.0.0"},
            "node_modules/d": {"version": "1.0.0"},
        },
    )

    parsed, graph = package_lock.parse(manifest)

    assert len(parsed.dependencies) == 2
    assert len(graph.nodes) == 3


# --- against locks npm actually wrote --------------------------------------


def test_a_real_lock_reads_every_package() -> None:
    """98 paths in the file, 92 packages in the graph: `debug@2.6.9` is
    installed at four places and is one package. `npm ls` counts 92 too."""
    parsed, graph = package_lock.parse(FIXTURES / "nested" / "package.json")

    assert len(graph.nodes) == 92
    assert len(parsed.dependencies) == 5  # 3 dependencies, 1 dev, 1 optional
    assert parsed.skipped == []


def test_one_package_installed_at_several_paths_is_one_node() -> None:
    """The identity is name and version, not where npm happened to put it."""
    _, graph = package_lock.parse(FIXTURES / "nested" / "package.json")

    assert len([k for k in graph.nodes if k.name == "debug" and k.version == "2.6.9"]) == 1


def test_a_real_lock_carries_two_copies_of_one_package() -> None:
    _, graph = package_lock.parse(FIXTURES / "nested" / "package.json")

    assert {k.version for k in graph.nodes if k.name == "ms"} == {"2.0.0", "2.1.1", "2.1.3"}


def test_a_real_lock_keeps_a_dotted_name_intact() -> None:
    """The name that OSV answers about; `lodash-merge` is not a package."""
    _, graph = package_lock.parse(FIXTURES / "nested" / "package.json")

    assert any(k.name == "lodash.merge" for k in graph.nodes)


def test_a_real_aliased_lock_uses_registry_names() -> None:
    _, graph = package_lock.parse(FIXTURES / "aliased" / "package.json")

    assert sorted(k.name for k in graph.roots) == ["debug", "lodash"]


# --- finding the lock ------------------------------------------------------


def test_the_lock_is_found_beside_the_manifest(tmp_path: Path) -> None:
    manifest = write(
        tmp_path, {"dependencies": {"a": "1"}}, {"node_modules/a": {"version": "1.0.0"}}
    )

    _, graph = package_lock.parse(manifest)

    assert len(graph.nodes) == 1


def test_the_lock_can_be_given_directly(tmp_path: Path) -> None:
    """Pointing at either half of the pair finds the other."""
    write(tmp_path, {"dependencies": {"a": "1"}}, {"node_modules/a": {"version": "1.0.0"}})

    _, graph = package_lock.parse(tmp_path / "package-lock.json")

    assert len(graph.nodes) == 1
